# Generated by Django 5.1.7 on 2025-04-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(db_column='pass', max_length=100)),
            ],
            options={
                'db_table': 'taikhoan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(db_column='masinhvien', max_length=10, primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=100)),
                ('noio', models.CharField(max_length=255)),
                ('diemhocphan', models.FloatField()),
                ('lophocphan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sinhvien',
                'managed': False,
            },
        ),
    ]
