# Generated by Django 5.1.7 on 2025-04-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HP',
            fields=[
                ('mahp', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('tenhp', models.CharField(max_length=50)),
                ('sotc', models.IntegerField()),
            ],
            options={
                'db_table': 'hocphan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('masv', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=50)),
                ('sdt', models.CharField(max_length=10)),
                ('ngaysinh', models.DateField()),
                ('nganhhoc', models.CharField(max_length=50)),
                ('lop', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'sinhvien',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
