# Generated by Django 5.1.7 on 2025-04-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hpghidanh_kqghidanh'),
    ]

    operations = [
        migrations.CreateModel(
            name='LH',
            fields=[
                ('malich', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('loaidangky', models.CharField(max_length=20)),
                ('namhoc', models.IntegerField()),
                ('hocky', models.IntegerField()),
                ('batdau', models.DateTimeField()),
                ('ketthuc', models.DateTimeField()),
            ],
            options={
                'db_table': 'lichhen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LHP',
            fields=[
                ('malhp', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('giangvien', models.CharField(blank=True, max_length=100, null=True)),
                ('sosvtoida', models.IntegerField(blank=True, null=True)),
                ('lichhoc', models.TextField(blank=True, null=True)),
                ('phonghoc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'lophocphan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LS',
            fields=[
                ('mals', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('hoatdong', models.CharField(max_length=20)),
                ('trangthai', models.CharField(max_length=20)),
                ('thoigian', models.DateTimeField()),
            ],
            options={
                'db_table': 'lichsu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NH',
            fields=[
                ('manganh', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tennganh', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nganhhoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('matk', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('matkhau', models.CharField(max_length=100)),
                ('tendangnhap', models.CharField(max_length=50, unique=True)),
                ('vaitro', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'taikhoan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTHT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tinhtrang', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tinhtranghoctap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTNS',
            fields=[
                ('manv', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('hoten_nv', models.CharField(max_length=100)),
                ('cccd_nv', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'nhanvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTSV',
            fields=[
                ('masv', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('hoten_sv', models.CharField(max_length=100)),
                ('cccd_sv', models.CharField(max_length=12)),
                ('lop', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sinhvien',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='HPGhiDanh',
        ),
        migrations.DeleteModel(
            name='KQGhidanh',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
