# Generated by Django 5.1.7 on 2025-04-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lh_lhp_ls_nh_taikhoan_ttht_ttns_ttsv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('GD', 'Ghi danh'), ('HP', 'Học phần')], max_length=2, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
