# Generated by Django 5.1.7 on 2025-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_allowedperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTDK',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mamh', models.CharField(max_length=10)),
                ('hinhthuc', models.CharField(max_length=10)),
                ('trangthai', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'trangthaidk',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AllowedPeriod',
        ),
    ]
