# Generated by Django 5.1.7 on 2025-05-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ttdk_delete_allowedperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='TM',
            fields=[
                ('malich', models.AutoField(primary_key=True, serialize=False)),
                ('batdau', models.DateTimeField()),
                ('ketthuc', models.DateTimeField()),
                ('loaidangky', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lichhen',
                'managed': False,
            },
        ),
    ]
